export const projects = [
  {
    title: 'Mapty',
    description: "Using HTML, CSS, JavaScript you'll learn how to build anpplication - from start to finish. The App is called Mapty and it is a simple workout logging app that allows users to log their workouts at a specific postion.",
      image: '/images/project1.jpg',
      tags: ['HTML', 'CSS', 'JavaScript'],
    source: 'https://github.com/Eren-Yeaager',
    visit: 'https://github.com/Eren-Yeaager/Mapty/tree/master/final',
    id: 0,
  },
  {
    title: 'G-G',
    description:"Developed a game using HTML, CSS, and JavaScript. The user has to input a random number between 1-20 which when compared to the number generated by the game decides whether the guess is higher or lower. If the number is equal to the number generated by the game, then the user win.",

    image: '/images/project2.jpg',
    tags: ['HTML','CSS', 'JavaScript'],
    source: 'https://github.com/Eren-Yeaager',
    visit: 'https://github.com/Eren-Yeaager/G-G',
    id: 1,
  },
  {
    title: 'Social Distancing with BLE Armband',
    description: "A cheap and easy to use BLE Armband for Social Distancing and enabling Touch Free solutions for COVID-19.",
    image:'/images/arduino_logo_1200x630-01.png',
    tags: ['Arduino'],
    visit: 'https://create.arduino.cc/projecthub/utkarshverma294/ble-armband-for-covid-19-b59417',
    id: 2,
  },
  {
    title: 'Trivia-Quiz',
    description: "Using React.js and Typescript developed a quiz game that enables user to write answers and then fetches data from a specific API to compare the answers given and then displays whether the answer is correct or incorrect. ",
      image: '/images/react.png',
      tags: ['React.js','Typescript'],
    source: 'https://github.com/Eren-Yeaager',
    visit: 'https://github.com/Eren-Yeaager/React-quiz',
    id: 3,
  },
  
  
];

export const TimeLineData = [
  { year: 2019, text: 'Started my journey', },
  { year: 2020, text: 'Learned the Front-end Technologies', },
  { year: 2021, text: 'Shared my projects with the world', },
   
];